# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('yelp_url', models.URLField()),
                ('phone', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('category_one', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
            ],
        ),
    ]
