# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('hometown', models.CharField(max_length=30)),
                ('num_friends', models.IntegerField()),
                ('age_range', models.IntegerField()),
                ('religion', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=30)),
            ],
        ),
    ]
