# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantLocation', models.CharField(max_length=50)),
                ('foodType', models.CharField(max_length=50)),
            ],
        ),
    ]
